[package]
name = "utf8-chars"
version = "0.1.0"
authors = ["Warlock <internalmike@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.4.11"
utf-8 = "0.7.5"
