[package]
name = "utf8-chars"
version = "0.1.2"
authors = ["warlock <internalmike@gmail.com>"]
description = "Char-per-char iterator and `read_char` method for `BufRead`."
readme = "README.md"
documentation = "https://docs.rs/utf8-chars/"
keywords = ["utf-8", "utf8", "chars", "iterator", "read_char"]
license = "MIT/Apache-2.0"
repository = "https://github.com/A1-Triard/utf8-chars"

[dependencies]
arrayvec = "0.5.0"

[dev-dependencies]
quickcheck = "0.9.0"
quickcheck_macros = "0.8.0"
