name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: '0 0 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: ["1.59", stable, beta, nightly]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - uses: actions/checkout@v2
    - name: build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: "--verbose"
    - name: test --tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: "--verbose --tests"
    - name: test --doc
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: "--verbose --doc"
    - name: doc
      uses: actions-rs/cargo@v1
      with:
        command: doc
        args: "--verbose"
    - name: build --release
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: "--verbose --release"
    - name: outdated
      uses: actions-rs/cargo@v1
      with:
        command: outdated
        args: "--verbose --aggresssive --root-deps-only --exit-code 1"
    - name: rustup component add clippy
      run: "rustup component add clippy"
    - name: clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: "--verbose"
